version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: souqsql-container
    environment:
      SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - souq-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "P@ssword123" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: ahmedhassanhero/souq-banimazar-api:latest
    container_name: souqapi-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BaniMazarMarketplaceDb;User Id=sa;Password=P@ssword123;TrustServerCertificate=true;
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - souq-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  souq-network:
    driver: bridge